- hosts: all
  roles:
    - common

- hosts: desktop
  vars:
    context: desktop
  vars_files:
    - git-desktop.yml
  roles:
    - apps-desktop
    - cli-tools
    - config-dev
    - fonts
    - gnome
    - k8s-cli-tools
    - morewaita
    - vim
    - warp
    - zsh

- hosts: work
  vars:
    context: work
  roles:
    - apps-work
    - cli-tools
    - docker
    - fonts
    - gnome
    - k8s-cli-tools
    - morewaita
    - vim
    - warp
    - zsh
