- hosts: desktop
  vars:
    context: desktop
  vars_files:
    - git-desktop.yml
  roles:
    - apps
    - cli-tools
    - fonts
    - git
    - gnome
    - k8s-cli-tools
    - morewaita
    - syncthing
    - vim
    - warp
    - zellij
    - zsh

- hosts: work
  vars:
    context: work
  roles:
    - apps
    - cli-tools
    - docker
    - fonts
    - gnome
    - k8s-cli-tools
    - morewaita
    - vim
    - warp
    - zellij
    - zsh

- hosts: nas
  roles:
    - appflowy-cloud
    - cloudflared
    - fresh-rss
    - papermc
    - portainer
    - transmission
