- hosts: all
  roles:
    - common

- hosts: desktop
  vars:
    context: desktop
  vars_files:
    - git-desktop.yml
  roles:
    - apps-desktop
    - gnome
    - config-dev
    - zsh
    - morewaita
    - warp
    - vim
    - fonts
    - cli-tools
    - k8s-cli-tools

- hosts: work
  vars:
    context: work
  roles:
    - apps-work
    - gnome
    - morewaita
    - warp
    - zsh
    - vim
    - fonts
    - docker
    - cli-tools
    - k8s-cli-tools
