- hosts: desktop
  vars:
    context: desktop
  vars_files:
    - git-desktop.yml
  roles:
    - apps
    - cli-tools
    - config-dev
    - fonts
    - gnome
    - k8s-cli-tools
    - morewaita
    - vim
    - warp
    - zellij
    - zsh

- hosts: work
  vars:
    context: work
  roles:
    - apps
    - cli-tools
    - docker
    - fonts
    - gnome
    - k8s-cli-tools
    - morewaita
    - vim
    - warp
    - zellij
    - zsh

- hosts: nas
  roles:
    - transmission
