- hosts: desktop
  vars:
    context: desktop
  vars_files:
    - git-desktop.yml
  roles:
    - adw-gtk3
    - apps
    - backup
    - cli-tools
    - coolercontrol
    - fonts
    - git
    - gnome
    - k8s-cli-tools
    - morewaita
    - syncthing
    - vim
    - zellij
    - zsh

- hosts: work
  vars:
    context: work
  roles:
    - adw-gtk3
    - apps
    - cli-tools
    - docker
    - fonts
    - gnome
    - k8s-cli-tools
    - morewaita
    - vim
    - zellij
    - zsh

- hosts: nas
  vars:
    context: nas
  roles:
    - audiobookshelf
    - cloudflared
    - fresh-rss
    - mealie
    - portainer
    - syncthing
    - transmission
