- hosts: all
  roles:
    - common
    - gnome

- hosts: desktop
  vars:
    context: desktop
  vars_files:
    - git-desktop.yml
  roles:
    - apps-desktop
    - config-dev
    - zsh

- hosts: work
  roles:
    - apps-work
    - gnome-work