- hosts: all
  roles:
    - common

- hosts: desktop
  vars:
    context: desktop
  vars_files:
    - git-desktop.yml
  roles:
    - apps-desktop
    - gnome
    - config-dev
    - zsh
    - morewaita
    - warp
    - vim

- hosts: work
  vars:
    context: work
  roles:
    - apps-work
    - gnome
    - morewaita
    - warp
    - vim
    - zsh
