- name: Install home flatpaks
  community.general.flatpak:
    name:
      - tv.plex.PlexDesktop
      - com.synology.SynologyDrive
      - io.gitlab.news_flash.NewsFlash
      - ch.protonmail.protonmail-bridge
      - com.protonvpn.www
      - de.haeckerfelix.Fragments
      - io.gitlab.librewolf-community