- name: Create Warp directory
  file:
    path: "{{ ansible_user_dir }}/Ansible/Warp"
    state: directory

- name: Download Warp
  ansible.builtin.get_url:
    url: https://app.warp.dev/download?package=appimage
    dest: "{{ ansible_user_dir }}/Ansible/Warp/Warp.AppImage"
    mode: "+x"
    owner: "{{ ansible_env['USER'] }}"
  run_once: true
  become: true

- name: Copy icon
  ansible.builtin.copy:
    src: "icon.png"
    dest: "{{ ansible_user_dir }}/Ansible/Warp/icon.png"
    owner: "{{ ansible_env['USER'] }}"
  become: true

- name: Add desktop file
  ansible.builtin.template:
    src: "Warp.desktop.j2"
    dest: "/usr/share/applications/Warp.desktop"
  become: true