- name: clone MoreWaita
  ansible.builtin.git:
    repo: https://github.com/somepaulo/MoreWaita.git
    depth: 1
    dest: "{{ ansible_user_dir }}/Ansible/MoreWaita"

- name: Install MoreWaita
  ansible.builtin.command: ./install.sh
  args:
    chdir: "{{ ansible_user_dir }}/Ansible/MoreWaita"
  become: true

- name: Set MoreWaita as current icon theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'MoreWaita'"