- name: Check if mise is installed
  ansible.builtin.command: mise --version
  register: result
  ignore_errors: true
  changed_when: false

- name: Create mise directory
  file:
    path: "{{ ansible_user_dir }}/Ansible/mise"
    state: directory
  when: result is failed

- name: Download mise install script
  ansible.builtin.get_url:
    url: https://mise.run
    dest: "{{ ansible_user_dir }}/Ansible/mise/install.sh"
    mode: "+x"
    owner: "{{ ansible_env['USER'] }}"
  when: result is failed

- name: Install mise
  command: "{{ ansible_user_dir }}/Ansible/mise/install.sh"
  when: result is failed