- name: Copy private SSH key
  ansible.builtin.copy:
    src: "{{ inventory_hostname }}/ssh/id_ed25519"
    dest: "{{ ansible_user_dir }}/.ssh/"
    mode: "0600"

- name: Copy public SSH key
  ansible.builtin.copy:
    src: "{{ inventory_hostname }}/ssh/id_ed25519.pub"
    dest: "{{ ansible_user_dir }}/.ssh/"
    mode: "0644"
