- name: install k8s cli tools
  community.general.homebrew:
    name:
      - helm
      - k9s
      - kind
      - kubecolor
      - minikube
  ignore_errors: true # will fail on arm64

- name: install k8s cli tools mise
  ansible.builtin.copy:
    src: "k8s.toml"
    dest: "{{ ansible_user_dir }}/.config/mise/conf.d/"
  notify: mise upgrade
