- name: clone AppFlowy-Cloud
  ansible.builtin.git:
    repo: https://github.com/AppFlowy-IO/AppFlowy-Cloud
    depth: 1
    dest: "/tmp/AppFlowy-Cloud"
    version: 0.7.23

- name: Copy .env file
  ansible.builtin.copy:
    src: "/tmp/AppFlowy-Cloud/deploy.env"
    dest: "/tmp/AppFlowy-Cloud/.env"
    remote_src: yes

- name: Set environment variables
  ansible.builtin.lineinfile:
    path: "/tmp/AppFlowy-Cloud/.env"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: 'POSTGRES_PASSWORD=', line: 'POSTGRES_PASSWORD={{ appflowy.postgres.password }}' }
    - { regexp: 'SUPABASE_PASSWORD=', line: 'SUPABASE_PASSWORD={{ appflowy.supabase.password }}' }
    - { regexp: 'GOTRUE_JWT_SECRET=', line: 'GOTRUE_JWT_SECRET={{ appflowy.gotrue.jwt.secret }}' }
    - { regexp: 'GOTRUE_ADMIN_EMAIL=', line: 'GOTRUE_ADMIN_EMAIL={{ appflowy.gotrue.admin.email }}' }
    - { regexp: 'GOTRUE_ADMIN_PASSWORD=', line: 'GOTRUE_ADMIN_PASSWORD={{ appflowy.gotrue.admin.password }}' }
    - { regexp: 'NGINX_PORT=', line: 'NGINX_PORT={{ appflowy.nginx.port }}' }
    - { regexp: 'NGINX_TLS_PORT=', line: 'NGINX_TLS_PORT={{ appflowy.nginx.tls_port }}' }
    - { regexp: 'APPFLOWY_MAILER_SMTP_USERNAME=', line: 'APPFLOWY_MAILER_SMTP_USERNAME={{ appflowy.mailer.email }}' }
    - { regexp: 'APPFLOWY_MAILER_SMTP_EMAIL=', line: 'APPFLOWY_MAILER_SMTP_EMAIL={{ appflowy.mailer.email }}' }
    - { regexp: 'APPFLOWY_MAILER_SMTP_PASSWORD=', line: 'APPFLOWY_MAILER_SMTP_PASSWORD={{ appflowy.mailer.password }}' }
    - { regexp: 'API_EXTERNAL_URL=', line: 'API_EXTERNAL_URL={{ appflowy.api.url }}' }
    - { regexp: 'APPFLOWY_S3_CREATE_BUCKET=', line: 'APPFLOWY_S3_CREATE_BUCKET=false' }
    - { regexp: 'APPFLOWY_S3_USE_MINIO=', line: 'APPFLOWY_S3_USE_MINIO=false' }

# FIXME: disabled for now, GOTRUE throws SIGSEGV errors
#- name: Run docker compose
#  community.docker.docker_compose_v2:
#    project_src: "/tmp/AppFlowy-Cloud"
#    docker_cli: /usr/local/bin/docker
#  become: true