- name: Remove unneeded packages
  ansible.builtin.package:
    name:
      - baobab
      - evince
      - gnome-boxes
      - gnome-calculator
      - gnome-calendar
      - gnome-clocks
      - gnome-connections
      - gnome-contacts
      - gnome-font-viewer
      - gnome-logs
      - gnome-maps
      - gnome-system-monitor
      - gnome-text-editor
      - gnome-weather
      - libreoffice-core
      - loupe
      - mediawriter
      - rhythmbox
      - snapshot
    state: absent
  become: true

- name: Install packages
  ansible.builtin.package:
    name:
      - ptyxis
  become: true
