- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  community.general.flatpak:
    name:
      - app.devsuite.Ptyxis
      - org.gnome.Calendar
      - org.gnome.clocks
      - org.gnome.Loupe
      - org.gnome.Snapshot
      - org.gnome.TextEditor
      - com.plexamp.Plexamp
      - net.nokyan.Resources
      - io.appflowy.AppFlowy
      - ca.desrt.dconf-editor
      - com.mattjakeman.ExtensionManager
      - org.mozilla.Thunderbird
      - org.gnome.gitlab.cheywood.Buffer
      - com.github.tchx84.Flatseal
      - org.libreoffice.LibreOffice
      - io.podman_desktop.PodmanDesktop