- name: Install docker dependencies
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
  become: true

- name: Add docker repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: "/etc/yum.repos.d/docker-ce.repo"
  become: true

- name: Install docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  become: true
