- name: Install desktop dnf packages
  ansible.builtin.dnf:
    name:
      - syncthing
  become: true

- name: Enable systemd service
  ansible.builtin.systemd_service:
    name: syncthing
    state: started
    enabled: true
    scope: user