- name: Install - RedHat
  ansible.builtin.include_tasks: install-redhat.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - context == "desktop"

- name: Install - Docker
  ansible.builtin.include_tasks: install-docker.yml
  when:
    - context == "nas"
