- name: Install - Linux
  ansible.builtin.include_tasks: install-linux-package.yml
  when:
    - context == "desktop"

- name: Install - Docker
  ansible.builtin.include_tasks: install-docker.yml
  when:
    - context == "nas"
