- name: Install - Linux
  ansible.builtin.include_tasks: install-linux-package.yml
  when: "'desktop' in group_names"

- name: Install - Docker
  ansible.builtin.include_tasks: install-docker.yml
  when: "'nas' in group_names"
