- name: Install zellij
  ansible.builtin.copy:
    src: "zellij.toml"
    dest: "{{ ansible_user_dir }}/.config/mise/conf.d/"
  notify: mise upgrade

- name: Copy zellij configuration
  ansible.builtin.copy:
    src: "config.kdl"
    dest: "{{ ansible_user_dir }}/.config/zellij/"
