- name: Create JetBrains Mono directory
  file:
    path: "{{ ansible_workspace_dir }}/JetBrainsMonoNF"
    state: directory
  register: create_dir_result

- name: Download and extract JetBrains Mono Nerd Font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip
    dest: "{{ ansible_workspace_dir }}/JetBrainsMonoNF"
    remote_src: yes
  when: create_dir_result.changed

- name: Copy font
  ansible.builtin.copy:
    src: "{{ ansible_workspace_dir }}/JetBrainsMonoNF/JetBrainsMonoNLNerdFont-Regular.ttf"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/"
    owner: "{{ ansible_env['USER'] }}"
  become: true
  when: create_dir_result.changed